<!-- templates/users/index.phtml -->
<a href="/users/new">Add new User</a>
<table>
    <?php foreach ($user as $data): ?>
        <div>
            <?= htmlspecialchars($data) ?>
        </div>
    <?php endforeach ?>
    <?php if (count($flash) > 0) : ?>
        <ul>
            <?php foreach ($flash as $messages) : ?>
                <?php foreach ($messages as $message) : ?>
                    <li><?= $message ?></li>
                <?php endforeach ?>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
</table>
