<form action="/users4" method="get">
    <input type="search" required name="term" placeholder="Enter id"  value="<?= htmlspecialchars($term) ?>">
</form>
<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <?= $user['id'] ?>
            </td>
            <td>
                <a href="/users4/<?= $user['id'] ?>"><?= $user['firstName'] ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>