<!-- templates/users/new.phtml -->
<a href="/users">User info</a>
<form action="/users" method="post">
    <?php if (isset($errors['id'])): ?>
    <div><?= $errors['id'] ?></div>
    <?php endif ?>
    <div>
        <label>
            Имя
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
        <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
    </div>
    <div>
        <label>
            Город
            <select name="user[city]">
                <option value="">Город</option>
                <option value="3">Москва</option>
                <option value="13">Пенза</option>
                <option  value="399">Томск</option>
            </select>
        </label>
        <?php if (isset($errors['city'])): ?>
            <div><?= $errors['city'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Sign Up">
</form>